### ISSUE TITLE
post mdx 이름 변경 건의

### ISSUE THREAD

**Issue by otterbits** [nerd-animals/na-log-engine#79]
### 기능 설명

post mdx 파일의 이름을 '주제-...'로 바꾸는 것이 어떨까요?(-는 소주제 및 띄어쓰기)

### 필요 이유(선택)

현재 post mdx의 이름은 ``순서-이름.mdx`` 로 구성돼있습니다.
하지만, 어떤 파일을 삭제 시 모든 파일의 이름을 변경해줘야합니다.
frontmatter에는 ``date``라는 필수값 및 고유값이 있으니 date로 순서정렬을 해주는 것이 편의성 면에서도 좋아보이는데 어떨까요?

**Comment by SanGyuk-Raccoon** [comment]
mdx 파일은 `slug`로써만 의미있게 설정하는 것으로 결정했습니다.

정렬은 날짜 기준으로 합니다.
